### ISSUE TITLE
$ONE_DIR 路径获取错误

### ISSUE THREAD

**Issue by wdssmq** [one-bash/one.bash#1]
## 描述问题

执行`one dep install`安装时报错：

> /usr/local/bin/one: line 124: /home/wdssmq/.one.bash/bin/bash/exit-codes.bash: No such file or directory

路径里多了 bin/

## 复现步骤

```bash
# 设置 one.bash 的安装路径
ONE_DIR=~/.one.bash
git clone --depth 1 https://github.com/one-bash/one.bash.git $ONE_DIR
# 注意：你需要确保 /usr/local/bin/ 在环境变量 PATH 中
sudo ln -s "$ONE_DIR/bin/one" /usr/local/bin/one

# 安装依赖
one dep install
/usr/local/bin/one: line 124: /home/wdssmq/.one.bash/bin/bash/exit-codes.bash: No such file or directory
```

### 上下文版本号

- 系统: Ubuntu 20.04 + wsl2

**Comment by adoyle-h** [comment]
What's the result of `echo $ONE_DIR` in your shell?

**Comment by adoyle-h** [comment]
Fixed. Please update to latest commit. Thanks
